#ifndef DOUGHAN_ALCATELSMSNOTYBL_CONSTVALUES_20140910__HPP__
#define DOUGHAN_ALCATELSMSNOTYBL_CONSTVALUES_20140910__HPP__


const char PREFIX_PER_LOG_LINE[]		= "\t\t\t\t\t\t\t";
const char SUFIX_PER_LOG_LINE[]			= "\r\n";


#endif